version: '3.7'

services:
  workspace:
    build:
      context: .
      dockerfile: docker/prod/node/Dockerfile
    image: nest-workspace
    restart: on-failure
    container_name: nest-workspace
    ports:
      - ${APP_PORT}:${APP_PORT}
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
    networks:
      - internal
    tty: true
    stdin_open: true
  mysql:
    image: mysql:8.0
    container_name: nest-database
    restart: unless-stopped
    tty: true
    command: --character-set-server=utf8mb4 --default-authentication-plugin=mysql_native_password
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - .mysql-data:/var/lib/mysql
    networks:
      - internal
networks:
  internal:
    name: internal
    driver: bridge
